import pyscf
from pyscf import scf, gto, mcscf, lib
import numpy as np
#from pyscf.fci import csf_solver
from pyscf.mcdcft import mcdcft

'''
This input file performs a potential energy scan of H2 using cBLYP-2 (density coherence functional with reparameterization). It will read the checkpoint files generated by example 01.
'''

def run(chkfile):
    mol = lib.chkfile.load_mol(chkfile)
    mol.verbose = 3
    mf = scf.RHF(mol)
    mc = mcdcft.CASSCF(mf, None, 2, 2, grids_level=6)
    mc.load_mcdcft_chk(chkfile)
    mc.recalculate_with_xc('0.92 * B88 , 1.59 * LYP', 
                            ot_name='cBLYP-2', dump_chk=chkfile)
    return mc


def scan():
    mo_coeff = None
    method = 'MC-DCFT'

    rrange = np.arange(0.5, 6.1, 0.1)

    for r in rrange:
        chkfile = f'{method}_{r:02.2f}.chk'
        mc = run(chkfile)
        

if __name__ == '__main__':
    lib.num_threads(2)
    scan()

