from pyscf import scf, gto, mcscf, lib, mcdcft
import numpy as np

'''
This input file performs a potential energy scan of H2 using cBLYP-2 (density coherence functional
with reparameterization). It will read the checkpoint files generated by example 01.
'''

dc_preset = dict(args=dict(f=mcdcft.dcfnal.f_v1, negative_rho=True), xc_code='0.92 * B88 , 1.59 * LYP')
mcdcft.dcfnal.register_dcfnal_('cBLYP-2', dc_preset)

def run(chkfile):
    mol = lib.chkfile.load_mol(chkfile)
    mol.verbose = 3
    mc = mcdcft.DCFT_base(mol, grids_level=6)
    mc.load_mcdcft_chk(chkfile)
    mc.recalculate_with_xc('cBLYP-2', dump_chk=chkfile)
    return mc


def scan():
    method = 'MC-DCFT'

    rrange = np.arange(0.5, 6.1, 0.1)

    for r in rrange:
        chkfile = f'{method}_{r:02.2f}.chk'
        run(chkfile)


if __name__ == '__main__':
    lib.num_threads(2)
    scan()

