name: Lint

on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install "flake8>=3.7.0"
      - name: Static analysis
        run: flake8 --config .flake8 pyscf
