#!/usr/bin/env python
# Copyright 2014-2026 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Bhavnesh Jangid

'''
Test Description: Testing the BP and DKH spin-orbit integrals generated by PySCF.
The reference integrals use a fixed speed of light and a fixed molecular
density matrix. This will test the socintegral file.

Test-1: Compare BP and DKH AMFI integrals with absolute references.
Test-2: Compare BP and DKH MMFI integrals with absolute references.
Test-3: Check spin-orbit integral shape, Hermiticity, and input validation.

'''

import unittest

import numpy as np
import scipy.linalg

from pyscf import ao2mo, gto, lib
from pyscf.siso import amfi, socaddons


# Fixed inputs used to generate the absolute references below.  LIGHT_SPEED is
# in atomic units, and FIXED_DENSITY is the spin-summed ROHF density for the
# triplet O/STO-3G test system.

# These values are generated with Pyscf (v2.14, 14fb93158ec9c97ae1d67462ea47b5b27ce63aca) 
# PySCF-Forge (commit:cbc3808b92cbc4a5fff2c7343349770de845a93c)

LIGHT_SPEED = 137.03599967994
FIXED_DENSITY = np.array([
    [2.1187086021338399, -0.50150666644447495, 0.0, 0.0, 0.0],
    [-0.50150666644447495, 2.1187086021338395, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 2.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 1.0],
])

def _soc_reference(yz, zy, xz, zx, xy, yx):
    reference = np.zeros((3, 5, 5), dtype=np.complex128)
    reference[0, 3, 4], reference[0, 4, 3] = 1j * yz, 1j * zy
    reference[1, 2, 4], reference[1, 4, 2] = 1j * xz, 1j * zx
    reference[2, 2, 3], reference[2, 3, 2] = 1j * xy, 1j * yx
    return reference


def _soc2e_jk_ao2mo(pmol, dm, mo1, mo3):
    """Reference implementation used before the direct shell contraction."""
    nao = dm.shape[0]
    eri = ao2mo.general(
        pmol, (mo3, mo1, mo3, mo1), intor='int2e_p1vxp1',
        aosym='s1', comp=3, compact=True)
    vj = np.asarray([
        np.einsum('ijkl,lk->ij', ao2mo.restore(1, eri[x], nao), dm)
        for x in range(3)])

    eri = ao2mo.general(
        pmol, (mo3, mo1, mo1, mo3), intor='int2e_p1vxp1',
        aosym='s1', comp=3, compact=True)
    vk = np.zeros_like(vj)
    for x in range(3):
        eri_x = ao2mo.restore(1, eri[x], nao)
        vk[x] = np.einsum('ijkl,jk->il', eri_x, dm)
        vk[x] += np.einsum('ijkl,li->kj', eri_x, dm)
    return vj, vk


# Absolute BP and DKH AMFI/MMFI integral tensors generated using LIGHT_SPEED
# and FIXED_DENSITY above.  Elements not listed are zero to numerical accuracy.
SOC_REFERENCES = {
    ('BP', 'AMFI'): _soc_reference(
        0.00042563489601017603, -0.000425634896010176,
        -0.0004256348960101775, 0.00042563489601017755,
        0.00042563489601017506, -0.00042563489601017506),
    ('BP', 'MMFI'): _soc_reference(
        0.00046289565575591003, -0.00046289565575591,
        -0.00043309417057218563, 0.0004330941705721856,
        0.00046289565575590905, -0.00046289565575590905),
    ('DKH', 'AMFI'): _soc_reference(
        0.00042565230824140045, -0.00042565230824140055,
        -0.00042565230824140185, 0.000425652308241402,
        0.00042565230824139963, -0.0004256523082413996),
    ('DKH', 'MMFI'): _soc_reference(
        0.0004629072160495022, -0.0004629064667000086,
        -0.0004331201028529131, 0.0004331201028529133,
        0.00046290646670000765, -0.00046290721604950135),
}


class KnownValues(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # The triplet O atom provides a small, nonzero SOC test case.  Use the
        # fixed density and speed of light documented above for every integral.
        cls.mol = gto.M(atom='O 0 0 0', basis='sto-3g', spin=2, verbose=0)
        cls.dm = FIXED_DENSITY.copy()
        cls.hso = {}
        with lib.temporary_env(lib.param, LIGHT_SPEED=LIGHT_SPEED):
            for ham in ('BP', 'DKH'):
                cls.hso[ham, 'AMFI'] = socaddons.socintegrals(
                    cls.mol, ham=ham)
                cls.hso[ham, 'MMFI'] = socaddons.socintegrals(
                    cls.mol, amf=False, mmf=True, ham=ham, dm=cls.dm)

    @classmethod
    def tearDownClass(cls):
        del cls.mol, cls.dm, cls.hso

    def test_bp_and_dkh_amfi_references(self):
        for ham in ('BP', 'DKH'):
            with self.subTest(ham=ham):
                hso = self.hso[ham, 'AMFI']
                self.assertEqual(
                    hso.shape, (3, self.mol.nao_nr(), self.mol.nao_nr()))
                np.testing.assert_allclose(
                    hso, SOC_REFERENCES[ham, 'AMFI'], atol=1e-10, rtol=0.0)

    def test_bp_and_dkh_mmfi_references(self):
        for ham in ('BP', 'DKH'):
            with self.subTest(ham=ham):
                hso = self.hso[ham, 'MMFI']
                np.testing.assert_allclose(
                    hso, SOC_REFERENCES[ham, 'MMFI'], atol=1e-10, rtol=0.0)

    def test_soc1e_and_soc2e_fns(self):
        with lib.temporary_env(lib.param, LIGHT_SPEED=LIGHT_SPEED):
            hso1e = socaddons.socintegrals(
                self.mol, ham='BP', soc1e=True, soc2e=False)
            hso2e = socaddons.socintegrals(
                self.mol, ham='BP', soc1e=False, soc2e=True)
        self.assertTrue(np.allclose(
            self.hso['BP', 'AMFI'], hso1e + hso2e,
            atol=1e-10, rtol=0.0))

    def test_diatomic_soc2e_direct_against_ao2mo(self):
        mol = gto.M(
            atom='O 0 0 0; F 0 0 1.3', basis='sto-3g', spin=1, verbose=0)
        rng = np.random.default_rng(12)
        dm = rng.standard_normal((mol.nao_nr(), mol.nao_nr()))
        dm = dm + dm.T

        hso2e_ref = np.zeros((3, mol.nao_nr(), mol.nao_nr()))
        atom = mol.copy()
        for ia, (b0, b1, p0, p1) in enumerate(mol.aoslice_by_atom()):
            with self.subTest(atom=mol.atom_symbol(ia)):
                atom._bas = mol._bas[b0:b1]
                pmol, ctr_coeff = atom.decontract_basis()
                ctr_coeff = scipy.linalg.block_diag(*ctr_coeff)
                mo1, mo3 = amfi.compute_kinematic_factors(
                    pmol, ctr_coeff, ham='DKH')
                dm_atom = dm[p0:p1, p0:p1]

                vj_ref, vk_ref = _soc2e_jk_ao2mo(
                    pmol, dm_atom, mo1, mo3)
                vj, vk = amfi.compute_soc2e_jk(pmol, dm_atom, mo1, mo3)
                np.testing.assert_allclose(vj, vj_ref, atol=1e-12, rtol=0.0)
                np.testing.assert_allclose(vk, vk_ref, atol=1e-12, rtol=0.0)
                hso2e_ref[:, p0:p1, p0:p1] = vj_ref - 1.5 * vk_ref

        hso2e = amfi.compute_hso2(mol, dm, ham='DKH')
        np.testing.assert_allclose(hso2e, hso2e_ref, atol=1e-12, rtol=0.0)


if __name__ == '__main__':
    unittest.main()
